# Generated by Django 5.0.7 on 2024-11-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
